const metiers = [
  'acteur',
  'agriculteur',
  'architecte',
  'archéologue',
  'avocat',
  'berger',
  'boucher',
  'boulanger',
  'bûcheron',
  'caissière',
  'chanteur',
  'coiffeur',
  'comptable',
  'cuisinier',
  'danseuse de ballet',
  'dentiste',
  'designer',
  'détective',
  'fleuriste',
  'footballeur',
  'garde forestier',
  'grutier',
  'généticien',
  'géologue',
  'infirmière',
  'informaticien',
  'journaliste',
  'libraire',
  'livreur de pizza',
  'magicien',
  'marionnettiste',
  'maréchal ferrant',
  'maître-nageur',
  'moniteur de ski',
  'médecin',
  'nageur',
  'océanologue',
  'orthophoniste',
  'peintre',
  'pharmacien',
  'photographe',
  'plombier',
  'policier',
  'professeur',
  'président',
  'psychiatre',
  'publiciste',
  'pédiatre',
  'pêcheur',
  'reporter',
  'réalisateur',
  'réparateur automobile',
  'sapeur-pompier',
  'scientifique',
  'serrurier',
  'serveur',
  'styliste',
  'toiletteur',
  'traducteur',
  'un pickpocket',
  'vétérinaire',
  'webmaster',
  'ébéniste',
  'éleveur de chiens',
]

const animaux = [
  'un anaconda',
  'un babouin',
  'un bernard l’ermite',
  'un bison',
  'un boa',
  'un caméléon',
  'un canard',
  'un chameau',
  'un chien de traineau',
  'un crabe',
  'un dauphin',
  'un dindon',
  'un dinosaure',
  'un escargot',
  'un faucon',
  'un hibou',
  'un hippocampe',
  'un héron',
  'un kangourou',
  'un koala',
  'un lama',
  'un lapin',
  'un lion',
  'un mille-pattes',
  'un moustique',
  'un mouton',
  'un panda',
  'un paon',
  'un papillon',
  'un paresseux',
  'un phoque',
  'un pic vert',
  'un pingouin',
  'un poisson clown',
  'un poulpe',
  'un raton laveur',
  'un raton-laveur',
  'un saumon',
  'un scarabée',
  'un scorpion',
  'un tapir',
  'un tatou',
  'un têtard',
  'un zèbre',
  'un écureuil',
  'un éléphant',
  'une autruche',
  'une biche',
  'une chauve-souris',
  'une coccinelle',
  'une fourmi',
  'une girafe',
  'une grenouille',
  'une hyène',
  'une libellule',
  'une loutre',
  'une marmotte',
  'une poule',
  'une souris',
  'une taupe',
  'une tortue',
  'une étoile de mer',
]

const actions = [
  'aller dans le train fantôme',
  'aller à la piscine',
  'aller à la pêche',
  'allumer le barbecue',
  'allumer un feu',
  'arriver en retard',
  'avoir la grippe',
  'changer le bébé',
  'changer une couche',
  'chercher ses clés',
  'couper un gâteau',
  'courir après le bus',
  'courir un marathon',
  'danser la valse',
  'emballer une momie',
  'escalader une montagne',
  'explorer une grotte',
  'faire de la boxe',
  'faire de la corde à sauter',
  'faire de la moto',
  'faire de la trotinette',
  'faire des claquettes',
  'faire des crêpes',
  'faire du patin à glace',
  'faire du surf',
  'faire la racaille',
  'faire la vaisselle',
  'faire le clown',
  'faire sauter une crêpe',
  'faire ses devoirs',
  'faire un câlin',
  'faire un tour en montgolfière',
  'faire une course de haies',
  'faire une galipette',
  'fêter son anniversaire',
  'jongler avec des pommes',
  'jouer au curling',
  'jouer avec un yoyo',
  'jouer du banjo',
  'jouer à pokemon',
  'lire du braille',
  'manger des spaghettis',
  'manger une glace',
  'marcher avec des échasses',
  'marcher dans le désert',
  'marcher sur des braise',
  'mâcher un chewing-gum',
  'nouer sa cravate',
  'planter un arbre',
  'prendre le train',
  'prendre l’ascenseur',
  'prendre l’escalator',
  'prendre un bain',
  'prendre un médicament (de votre choix…)',
  'presser une orange',
  'promener le chien',
  'recevoir une médaille',
  'regarder la télé',
  'rencontrer un martien',
  'sauter à la corde',
  'se battre à l’épée',
  'se faire cuire un œuf',
  'se préparer un café',
  'se transformer en loup-garou',
  'sortir les poubelles',
  'tirer à l’arc',
  'traire une vache',
  'tuer une araignée avec une bombe insecticide',
  'téléphoner à mamie',
  'vendre un tapis',
  'éplucher des patates',
  'étendre du linge',
  'être blonde',
  'être lunatique',
  'être malade en bateau',
]

const actionCoquines = [ // 1 fait a 2
  'fister',
  'doigter',
  'enculer',
  'caresser',
  'masturber',
  'epiler',
  'embrasser',
  'fouetter',
  'sucer',
  'faire une fellation a',
  'donner une erection a',
  'raser les fesses a',
  'ecarter les jambes a',
  'rouler une pelle a',
  'masser les pieds a',
  'masser les oreilles a',
  'mettre des menottes a',
]

const personnages = [
  'alice (au pays des merveilles)',
  'archimède',
  'astérix le gaulois',
  'barack obama',
  'bill gates',
  'bugs bunny',
  'casimir',
  'charlie chaplin',
  'cindy sanders',
  'claude françois',
  'cléopâtre',
  'cousteau',
  'cyril lignac',
  'céline dion',
  'dark vador',
  'einstein',
  'gad elmaleh',
  'galilée',
  'gaston lagaffe',
  'harry potter',
  'homer simpson',
  'isaac newton',
  'jack sparrow',
  'johnny halliday',
  'la joconde',
  'la reine d’angleterre',
  'lancelot',
  'le dalaï lama',
  'le génie de la lampe',
  'louis de funès',
  'louis xiv',
  'lucky luke',
  'l’abbé pierre',
  'mac gyver',
  'messi',
  'mickey',
  'mimi mathy',
  'moi meme',
  'mr bean',
  'napoléon',
  'picasso',
  'rayman',
  'shreck',
  'steve job',
  'superman',
  'tintin',
  'un bisounours',
  'un chef indien',
  'yannick noah',
  'zinedine zidane',
]

const expressions = [
  'anguille sous roche',
  'avoir la moutarde qui monte au nez',
  'avoir le cafard',
  'avoir les crocs',
  'avoir les yeux plus gros que le ventre',
  'avoir l’estomac dans les talons',
  'avoir plusieurs cordes à son arc',
  'avoir un poil dans la main',
  'avoir une araignée au plafond',
  'bailler aux corneilles',
  'comme on fait son lit, on se couche',
  'copains comme cochons',
  'courir sur le haricot',
  'devoir une fière chandelle',
  'dire ses 4 vérités',
  'donner de la confiture à un cochon',
  'donner sa langue au chat',
  'faut pas pousser mémé dans les orties',
  'fier comme un pou',
  'filer à l’anglaise',
  'jeter le bébé avec l’eau du bain',
  'la bave du crapaud n’atteint pas la blanche colombe',
  'la goutte d’eau qui fait déborder le vase',
  'la poule aux oeufs d’or',
  'l’habit ne fait pas le moine',
  'mentir comme un arracheur de dents',
  'mettre la main à la pâte',
  'mettre son grain de sel',
  'n’avoir pas froid aux yeux',
  'passer comme un lettre à la poste',
  'pleurer comme une madeleine',
  'poser un lapin',
  'pousser comme un champignon',
  'péter plus haut que son cul',
  'raconter des salades',
  'remettre les pendules à l’heure',
  'remuer le couteau dans la plaie',
  'revenir bredouille',
  'rire jaune',
  'ronfler comme un loir',
  'rouler des yeux de merlan frit',
  'rouler à tombeau ouvert',
  'se faire un sang d’encre',
  'se mettre en 4',
  's’ennuyer comme un rat mort',
  'tirer le diable par la queue',
  'tirer les vers du nez',
  'tomber dans les pommes',
  'toucher du bois',
  'tuer le temps',
  'tête de linotte',
  'un froid de canard',
  'un moulin à paroles',
  'vouloir le beurre et l’argent du beurre',
  'épée de damoclès',
  'être au bout du rouleau',
  'être au pied du mur',
  'être muet comme une carpe',
  'être sage comme une image',
  'être sourd comme un pot',
  'être un ours mal léché',
]

const who = [
  ...metiers,
  ...personnages,
  ...animaux,
]

const what = [
  ...actions,
  // ...expressions,
]

const random = list => list[Math.floor(Math.random() * list.length)]

document.mim = () => `Je suis ${random(who)}, je dois ${random(what)}`
document.mimc = () => `Je suis ${random(who)}, je dois ${random(actionCoquines)} ${random(personnages)}`
