const metiers = [
  'bûcheron',
  'boulanger',
  'vétérinaire',
  'boucher',
  'serveur',
  'ébéniste',
  'scientifique',
  'policier',
  'réparateur automobile',
  'styliste',
  'toiletteur',
  'professeur',
  'plombier',
  'coiffeur',
  'médecin',
  'maréchal ferrant',
  'berger',
  'infirmière',
  'agriculteur',
  'peintre',
  'caissière',
  'grutier',
  'avocat',
  'acteur',
  'reporter',
  'président',
  'éleveur de chiens',
  'informaticien',
  'cuisinier',
  'détective',
  'publiciste',
  'fleuriste',
  'océanologue',
  'dentiste',
  'nageur',
  'serrurier',
  'pharmacien',
  'garde forestier',
  'architecte',
  'traducteur',
  'archéologue',
  'maître-nageur',
  'généticien',
  'livreur de pizza',
  'comptable',
  'moniteur de ski',
  'psychiatre',
  'journaliste',
  'footballeur',
  'webmaster',
  'orthophoniste',
  'libraire',
  'réalisateur',
  'sapeur-pompier',
  'chanteur',
  'marionnettiste',
  'pédiatre',
  'géologue',
  'designer',
  'danseuse de ballet',
  'un pickpocket',
  'magicien',
  'photographe',
  'pêcheur',
]

const animaux = [
  'un moustique',
  'un crabe',
  'un pingouin',
  'un héron',
  'une girafe',
  'un panda',
  'un écureuil',
  'un lion',
  'un hibou',
  'un scarabée',
  'un lama',
  'un babouin',
  'une marmotte',
  'un dauphin',
  'un bernard l’ermite',
  'un mouton',
  'un canard',
  'un bison',
  'un boa',
  'un chameau',
  'une autruche',
  'un papillon',
  'un zèbre',
  'un koala',
  'une fourmi',
  'une souris',
  'une taupe',
  'un raton-laveur',
  'une grenouille',
  'une biche',
  'un escargot',
  'un phoque',
  'une tortue',
  'un dinosaure',
  'un tatou',
  'un chien de traineau',
  'une étoile de mer',
  'un caméléon',
  'une loutre',
  'un paon',
  'un kangourou',
  'une poule',
  'une hyène',
  'un faucon',
  'un anaconda',
  'un scorpion',
  'une coccinelle',
  'un têtard',
  'un saumon',
  'un mille-pattes',
  'un hippocampe',
  'une libellule',
  'un tapir',
  'un poisson clown',
  'un raton laveur',
  'un pic vert',
  'une chauve-souris',
  'un poulpe',
  'un lapin',
  'un dindon',
  'un paresseux',
  'un éléphant',
]

const actions = [
  'aller dans le train fantôme',
  'aller à la piscine',
  'aller à la pêche',
  'allumer le barbecue',
  'allumer un feu',
  'arriver en retard',
  'avoir la grippe',
  'changer le bébé',
  'changer une couche',
  'chercher ses clés',
  'couper un gâteau',
  'courir après le bus',
  'courir un marathon',
  'danser la valse',
  'emballer une momie',
  'escalader une montagne',
  'explorer une grotte',
  'faire de la boxe',
  'faire de la corde à sauter',
  'faire de la moto',
  'faire de la trotinette',
  'faire des claquettes',
  'faire des crêpes',
  'faire du patin à glace',
  'faire du surf',
  'faire la racaille',
  'faire la vaisselle',
  'faire le clown',
  'faire sauter une crêpe',
  'faire ses devoirs',
  'faire un câlin',
  'faire un tour en montgolfière',
  'faire une course de haies',
  'faire une galipette',
  'fêter son anniversaire',
  'jongler avec des pommes',
  'jouer au curling',
  'jouer avec un yoyo',
  'jouer du banjo',
  'jouer à pokemon',
  'lire du braille',
  'manger des spaghettis',
  'manger une glace',
  'marcher avec des échasses',
  'marcher dans le désert',
  'marcher sur des braise',
  'mâcher un chewing-gum',
  'nouer sa cravate',
  'planter un arbre',
  'prendre le train',
  'prendre l’ascenseur',
  'prendre l’escalator',
  'prendre un bain',
  'prendre un médicament (de votre choix…)',
  'presser une orange',
  'promener le chien',
  'recevoir une médaille',
  'regarder la télé',
  'rencontrer un martien',
  'sauter à la corde',
  'se battre à l’épée',
  'se faire cuire un œuf',
  'se préparer un café',
  'se transformer en loup-garou',
  'sortir les poubelles',
  'tirer à l’arc',
  'traire une vache',
  'tuer une araignée avec une bombe insecticide',
  'téléphoner à mamie',
  'vendre un tapis',
  'éplucher des patates',
  'étendre du linge',
  'être blonde',
  'être lunatique',
  'être malade en bateau',
]

const actionCoquines = [ // 1 fait a 2
  'fister',
  'doigter',
  'enculer',
  'caresser',
  'masturber',
  'epiler',
  'embrasser',
  'fouetter',
  'sucer',
  'faire une fellation a',
  'donner une erection a',
  'raser les fesses a',
  'ecarter les jambes a',
  'rouler une pelle a',
  'masser les pieds a',
  'masser les oreilles a',
  'mettre des menottes a',
]

const personnages = [
  'moi meme',
  'un chef indien',
  'harry potter',
  'lancelot',
  'superman',
  'barack obama',
  'tintin',
  'rayman',
  'einstein',
  'alice (au pays des merveilles)',
  'jack sparrow',
  'napoléon',
  'mickey',
  'cousteau',
  'bugs bunny',
  'johnny halliday',
  'lucky luke',
  'charlie chaplin',
  'la joconde',
  'dark vador',
  'le génie de la lampe',
  'shreck',
  'le dalaï lama',
  'un bisounours',
  'la reine d’angleterre',
  'claude françois',
  'gaston lagaffe',
  'cindy sanders',
  'messi',
  'picasso',
  'casimir',
  'steve job',
  'louis de funès',
  'galilée',
  'cyril lignac',
  'archimède',
  'l’abbé pierre',
  'louis xiv',
  'céline dion',
  'cléopâtre',
  'mr bean',
  'yannick noah',
  'isaac newton',
  'homer simpson',
  'gad elmaleh',
  'astérix le gaulois',
  'bill gates',
  'mac gyver',
  'mimi mathy',
  'zinedine zidane',
]

const expressions = [
  'ronfler comme un loir',
  'avoir les yeux plus gros que le ventre',
  'anguille sous roche',
  'tomber dans les pommes',
  'mettre son grain de sel',
  'être un ours mal léché',
  'un froid de canard',
  'poser un lapin',
  'filer à l’anglaise',
  'fier comme un pou',
  'l’habit ne fait pas le moine',
  'mettre la main à la pâte',
  'avoir une araignée au plafond',
  'rouler des yeux de merlan frit',
  'la poule aux oeufs d’or',
  'bailler aux corneilles',
  'revenir bredouille',
  'raconter des salades',
  'vouloir le beurre et l’argent du beurre',
  'être au bout du rouleau',
  'devoir une fière chandelle',
  'avoir un poil dans la main',
  'comme on fait son lit, on se couche',
  'passer comme un lettre à la poste',
  'péter plus haut que son cul',
  'rouler à tombeau ouvert',
  'la goutte d’eau qui fait déborder le vase',
  's’ennuyer comme un rat mort',
  'copains comme cochons',
  'donner sa langue au chat',
  'remettre les pendules à l’heure',
  'jeter le bébé avec l’eau du bain',
  'faut pas pousser mémé dans les orties',
  'se mettre en 4',
  'tête de linotte',
  'épée de damoclès',
  'avoir le cafard',
  'tirer le diable par la queue',
  'avoir l’estomac dans les talons',
  'pousser comme un champignon',
  'toucher du bois',
  'tirer les vers du nez',
  'donner de la confiture à un cochon',
  'courir sur le haricot',
  'tuer le temps',
  'avoir la moutarde qui monte au nez',
  'être sourd comme un pot',
  'pleurer comme une madeleine',
  'rire jaune',
  'n’avoir pas froid aux yeux',
  'la bave du crapaud n’atteint pas la blanche colombe',
  'être au pied du mur',
  'dire ses 4 vérités',
  'être sage comme une image',
  'mentir comme un arracheur de dents',
  'un moulin à paroles',
  'être muet comme une carpe',
  'avoir les crocs',
  'se faire un sang d’encre',
  'avoir plusieurs cordes à son arc',
  'remuer le couteau dans la plaie',
]

const who = [
  ...metiers,
  ...personnages,
  ...animaux,
]

const what = [
  ...actions,
  // ...expressions,
]

const random = list => list[Math.floor(Math.random() * list.length)]

document.mim = () => `Je suis ${random(who)}, je dois ${random(what)}`
document.mimc = () => `Je suis ${random(who)}, je dois ${random(actionCoquines)} ${random(personnages)}`
